<?xml version="1.0" encoding="utf-8"?><Database Name="Envanter" Class="DatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=RENCLNT01;Initial Catalog=Envanter;Integrated Security=True" SettingsObjectName="Envanter.Properties.Settings" SettingsPropertyName="EnvanterConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Cariler" Member="Carilers">
    <Type Name="Cariler">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CariKodu" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="CariAdi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VergiDairesi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="VergiNo" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Ulke" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Sehir" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Ilce" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Adres" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="WebAdres" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Yetkili" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="YetkiliEmail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Telefon" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(16)" CanBeNull="true" />
      <Column Name="SaveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SaveUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EditUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Cariler_Kurumlar" Member="Kurumlars" ThisKey="ID" OtherKey="CariID" Type="Kurumlar" />
    </Type>
  </Table>
  <Table Name="dbo.Depolar" Member="Depolars">
    <Type Name="Depolar">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DepoKodu" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DepoAdi" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SaveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SaveUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EditUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Depolar_KullaniciDepoYetki" Member="KullaniciDepoYetkis" ThisKey="ID" OtherKey="DepoID" Type="KullaniciDepoYetki" />
      <Association Name="Depolar_Stoklar" Member="Stoklars" ThisKey="ID" OtherKey="DepoID" Type="Stoklar" />
    </Type>
  </Table>
  <Table Name="dbo.StokGruplari" Member="StokGruplaris">
    <Type Name="StokGruplari">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GrupAdi" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GrupKodu" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="SaveUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SaveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EditUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="StokGruplari_StokKartlari" Member="StokKartlaris" ThisKey="ID" OtherKey="GrupID" Type="StokKartlari" />
    </Type>
  </Table>
  <Table Name="dbo.StokKartlari" Member="StokKartlaris">
    <Type Name="StokKartlari">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StokKartKodu" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="StokAdi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GrupID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SaveUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SaveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EditUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="StokKartlari_Stoklar" Member="Stoklars" ThisKey="ID" OtherKey="StokKartID" Type="Stoklar" />
      <Association Name="StokGruplari_StokKartlari" Member="StokGruplari" ThisKey="GrupID" OtherKey="ID" Type="StokGruplari" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_StokHareketleri" Member="VW_StokHareketleris">
    <Type Name="VW_StokHareketleri">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GCKodu" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="StokKodu" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="StokAdi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PartNo" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SeriNo" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Tarih" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="HastaneAdi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GrupAdi" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Kurumlar" Member="Kurumlars">
    <Type Name="Kurumlar">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CariID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KurumKodu" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="KurumAdi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ulke" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Sehir" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Ilce" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Adres" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="WebAdres" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Yetkili1" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Yetkili1Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Yetkili2" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Yetkili2Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Telefon" Type="System.String" DbType="NVarChar(18)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(18)" CanBeNull="true" />
      <Column Name="SaveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SaveUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EditUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Kurumlar_StokHareketleri" Member="StokHareketleris" ThisKey="ID" OtherKey="KurumID" Type="StokHareketleri" />
      <Association Name="Cariler_Kurumlar" Member="Cariler" ThisKey="CariID" OtherKey="ID" Type="Cariler" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StokHareketleri" Member="StokHareketleris">
    <Type Name="StokHareketleri">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StokID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KurumID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Aciklama" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Tur" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Tarih" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SaveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SaveUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EditUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DepoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Kurumlar_StokHareketleri" Member="Kurumlar" ThisKey="KurumID" OtherKey="ID" Type="Kurumlar" IsForeignKey="true" />
      <Association Name="Stoklar_StokHareketleri" Member="Stoklar" ThisKey="StokID" OtherKey="ID" Type="Stoklar" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_Yetkiler" Member="VW_Yetkilers">
    <Type Name="VW_Yetkiler">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KullaniciAdi" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="Rol" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Aktif" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.KullaniciRol" Member="KullaniciRols">
    <Type Name="KullaniciRol">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RolID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Aktif" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Roller_KullaniciRol" Member="Roller" ThisKey="RolID" OtherKey="ID" Type="Roller" IsForeignKey="true" />
      <Association Name="Kullanicilar_KullaniciRol" Member="Kullanicilar" ThisKey="UserID" OtherKey="ID" Type="Kullanicilar" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Roller" Member="Rollers">
    <Type Name="Roller">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Rol" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="Roller_KullaniciRol" Member="KullaniciRols" ThisKey="ID" OtherKey="RolID" Type="KullaniciRol" />
    </Type>
  </Table>
  <Table Name="dbo.Kullanicilar" Member="Kullanicilars">
    <Type Name="Kullanicilar">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KullaniciAdi" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="Ad" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Soyad" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="Sifre" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="LastLogin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Kullanicilar_KullaniciRol" Member="KullaniciRols" ThisKey="ID" OtherKey="UserID" Type="KullaniciRol" />
      <Association Name="Kullanicilar_KullaniciDepoYetki" Member="KullaniciDepoYetkis" ThisKey="ID" OtherKey="UserID" Type="KullaniciDepoYetki" />
    </Type>
  </Table>
  <Table Name="dbo.KullaniciDepoYetki" Member="KullaniciDepoYetkis">
    <Type Name="KullaniciDepoYetki">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DepoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Aktif" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Depolar_KullaniciDepoYetki" Member="Depolar" ThisKey="DepoID" OtherKey="ID" Type="Depolar" IsForeignKey="true" />
      <Association Name="Kullanicilar_KullaniciDepoYetki" Member="Kullanicilar" ThisKey="UserID" OtherKey="ID" Type="Kullanicilar" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_KullaniciDepo" Member="VW_KullaniciDepos">
    <Type Name="VW_KullaniciDepo">
      <Column Name="UserID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KullaniciAdi" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="DepoAdi" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Aktif" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DepoID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Stoklar" Member="Stoklars">
    <Type Name="Stoklar">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StokKartID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OemID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DepoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Tipi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StokKodu" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PartNo" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="SeriNo" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Label" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AlisFiyat" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="SatisFiyat" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="Durum" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Raf" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Aciklama" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Image" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SaveUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SaveDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EditUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Stoklar_StokHareketleri" Member="StokHareketleris" ThisKey="ID" OtherKey="StokID" Type="StokHareketleri" />
      <Association Name="Stoklar_Stoklar" Member="Stoklars" ThisKey="ID" OtherKey="OemID" Type="Stoklar" />
      <Association Name="Depolar_Stoklar" Member="Depolar" ThisKey="DepoID" OtherKey="ID" Type="Depolar" IsForeignKey="true" />
      <Association Name="StokKartlari_Stoklar" Member="StokKartlari" ThisKey="StokKartID" OtherKey="ID" Type="StokKartlari" IsForeignKey="true" />
      <Association Name="Stoklar_Stoklar" Member="Stoklar1" ThisKey="OemID" OtherKey="ID" Type="Stoklar" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VW_Oem" Member="VW_Oems">
    <Type Name="VW_Oem">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DepoID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Tipi" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OemID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GrupAdi" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="StokAdi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SeriNo" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="PartNo" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Durum" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Aciklama" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
    </Type>
  </Table>
</Database>